version: '3.8'

services:
  vws-app:
    image: 711678334703.dkr.ecr.ap-northeast-2.amazonaws.com/vws-app:latest
    container_name: vws-app
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
