<script lang="ts">
  import { onMount } from 'svelte'
  import { themeManager, currentTheme, isDark, isAuto } from '$lib/stores/theme'

  // Initialize theme on mount
  onMount(() => {
    // Theme is already initialized in the store
  })

  // Apply theme to document
  $effect(() => {
    const theme = $currentTheme
    const isDarkTheme = $isDark
    const isAutoTheme = $isAuto

    // Update document attributes
    document.documentElement.setAttribute('data-theme', theme)
    document.documentElement.setAttribute('data-color-scheme', theme)

    if (isDarkTheme) {
      document.documentElement.classList.add('dark')
    } else {
      document.documentElement.classList.remove('dark')
    }

    // Update meta theme-color for mobile browsers
    const metaThemeColor = document.querySelector('meta[name="theme-color"]')
    if (metaThemeColor) {
      metaThemeColor.setAttribute('content', isDarkTheme ? '#1a1a1a' : '#ffffff')
    }

    // Update CSS custom properties
    updateCSSVariables(theme, isDarkTheme)
  })

  // Update CSS custom properties based on theme
  function updateCSSVariables(theme: string, isDark: boolean) {
    const root = document.documentElement

    // Base colors
    const colors = {
      light: {
        '--color-background': '#ffffff',
        '--color-surface': '#f8f9fa',
        '--color-surface-elevated': '#ffffff',
        '--color-border': '#e9ecef',
        '--color-border-light': '#f1f3f4',
        '--color-text': '#212529',
        '--color-text-secondary': '#6c757d',
        '--color-text-muted': '#adb5bd',
        '--color-primary': '#007bff',
        '--color-primary-hover': '#0056b3',
        '--color-primary-light': '#e3f2fd',
        '--color-success': '#28a745',
        '--color-warning': '#ffc107',
        '--color-error': '#dc3545',
        '--color-info': '#17a2b8',
        '--color-shadow': 'rgba(0, 0, 0, 0.1)',
        '--color-shadow-light': 'rgba(0, 0, 0, 0.05)',
        '--color-overlay': 'rgba(0, 0, 0, 0.5)',
        '--color-overlay-light': 'rgba(0, 0, 0, 0.1)',
        '--color-gradient-start': '#f8f9fa',
        '--color-gradient-end': '#e9ecef',
        '--color-code-background': '#f8f9fa',
        '--color-code-border': '#e9ecef',
        '--color-table-header': '#f8f9fa',
        '--color-table-row': '#ffffff',
        '--color-table-row-hover': '#f8f9fa',
        '--color-input-background': '#ffffff',
        '--color-input-border': '#ced4da',
        '--color-input-focus': '#007bff',
        '--color-button-primary': '#007bff',
        '--color-button-primary-hover': '#0056b3',
        '--color-button-secondary': '#6c757d',
        '--color-button-secondary-hover': '#545b62',
        '--color-button-success': '#28a745',
        '--color-button-success-hover': '#1e7e34',
        '--color-button-warning': '#ffc107',
        '--color-button-warning-hover': '#e0a800',
        '--color-button-error': '#dc3545',
        '--color-button-error-hover': '#c82333',
        '--color-button-info': '#17a2b8',
        '--color-button-info-hover': '#138496',
        '--color-button-ghost': 'transparent',
        '--color-button-ghost-hover': '#f8f9fa',
        '--color-button-ghost-text': '#6c757d',
        '--color-button-ghost-text-hover': '#212529',
        '--color-button-ghost-border': '#e9ecef',
        '--color-button-ghost-border-hover': '#dee2e6',
        '--color-button-ghost-primary': '#007bff',
        '--color-button-ghost-primary-hover': '#0056b3',
        '--color-button-ghost-primary-text': '#007bff',
        '--color-button-ghost-primary-text-hover': '#ffffff',
        '--color-button-ghost-primary-border': '#007bff',
        '--color-button-ghost-primary-border-hover': '#007bff',
        '--color-button-ghost-success': '#28a745',
        '--color-button-ghost-success-hover': '#1e7e34',
        '--color-button-ghost-success-text': '#28a745',
        '--color-button-ghost-success-text-hover': '#ffffff',
        '--color-button-ghost-success-border': '#28a745',
        '--color-button-ghost-success-border-hover': '#28a745',
        '--color-button-ghost-warning': '#ffc107',
        '--color-button-ghost-warning-hover': '#e0a800',
        '--color-button-ghost-warning-text': '#ffc107',
        '--color-button-ghost-warning-text-hover': '#212529',
        '--color-button-ghost-warning-border': '#ffc107',
        '--color-button-ghost-warning-border-hover': '#ffc107',
        '--color-button-ghost-error': '#dc3545',
        '--color-button-ghost-error-hover': '#c82333',
        '--color-button-ghost-error-text': '#dc3545',
        '--color-button-ghost-error-text-hover': '#ffffff',
        '--color-button-ghost-error-border': '#dc3545',
        '--color-button-ghost-error-border-hover': '#dc3545',
        '--color-button-ghost-info': '#17a2b8',
        '--color-button-ghost-info-hover': '#138496',
        '--color-button-ghost-info-text': '#17a2b8',
        '--color-button-ghost-info-text-hover': '#ffffff',
        '--color-button-ghost-info-border': '#17a2b8',
        '--color-button-ghost-info-border-hover': '#17a2b8',
        '--color-button-ghost-size-sm': '8px 12px',
        '--color-button-ghost-size-md': '10px 16px',
        '--color-button-ghost-size-lg': '12px 20px',
        '--color-button-ghost-size-xl': '14px 24px',
        '--color-button-ghost-size-2xl': '16px 28px',
        '--color-button-ghost-size-3xl': '18px 32px',
        '--color-button-ghost-size-4xl': '20px 36px',
        '--color-button-ghost-size-5xl': '22px 40px',
        '--color-button-ghost-size-6xl': '24px 44px',
        '--color-button-ghost-size-7xl': '26px 48px',
        '--color-button-ghost-size-8xl': '28px 52px',
        '--color-button-ghost-size-9xl': '30px 56px',
        '--color-button-ghost-size-10xl': '32px 60px',
        '--color-button-ghost-size-11xl': '34px 64px',
        '--color-button-ghost-size-12xl': '36px 68px',
        '--color-button-ghost-size-13xl': '38px 72px',
        '--color-button-ghost-size-14xl': '40px 76px',
        '--color-button-ghost-size-15xl': '42px 80px',
        '--color-button-ghost-size-16xl': '44px 84px',
        '--color-button-ghost-size-17xl': '46px 88px',
        '--color-button-ghost-size-18xl': '48px 92px',
        '--color-button-ghost-size-19xl': '50px 96px',
        '--color-button-ghost-size-20xl': '52px 100px',
        '--color-button-ghost-size-21xl': '54px 104px',
        '--color-button-ghost-size-22xl': '56px 108px',
        '--color-button-ghost-size-23xl': '58px 112px',
        '--color-button-ghost-size-24xl': '60px 116px',
        '--color-button-ghost-size-25xl': '62px 120px',
        '--color-button-ghost-size-26xl': '64px 124px',
        '--color-button-ghost-size-27xl': '66px 128px',
        '--color-button-ghost-size-28xl': '68px 132px',
        '--color-button-ghost-size-29xl': '70px 136px',
        '--color-button-ghost-size-30xl': '72px 140px',
        '--color-button-ghost-size-31xl': '74px 144px',
        '--color-button-ghost-size-32xl': '76px 148px',
        '--color-button-ghost-size-33xl': '78px 152px',
        '--color-button-ghost-size-34xl': '80px 156px',
        '--color-button-ghost-size-35xl': '82px 160px',
        '--color-button-ghost-size-36xl': '84px 164px',
        '--color-button-ghost-size-37xl': '86px 168px',
        '--color-button-ghost-size-38xl': '88px 172px',
        '--color-button-ghost-size-39xl': '90px 176px',
        '--color-button-ghost-size-40xl': '92px 180px',
        '--color-button-ghost-size-41xl': '94px 184px',
        '--color-button-ghost-size-42xl': '96px 188px',
        '--color-button-ghost-size-43xl': '98px 192px',
        '--color-button-ghost-size-44xl': '100px 196px',
        '--color-button-ghost-size-45xl': '102px 200px',
        '--color-button-ghost-size-46xl': '104px 204px',
        '--color-button-ghost-size-47xl': '106px 208px',
        '--color-button-ghost-size-48xl': '108px 212px',
        '--color-button-ghost-size-49xl': '110px 216px',
        '--color-button-ghost-size-50xl': '112px 220px',
        '--color-button-ghost-size-51xl': '114px 224px',
        '--color-button-ghost-size-52xl': '116px 228px',
        '--color-button-ghost-size-53xl': '118px 232px',
        '--color-button-ghost-size-54xl': '120px 236px',
        '--color-button-ghost-size-55xl': '122px 240px',
        '--color-button-ghost-size-56xl': '124px 244px',
        '--color-button-ghost-size-57xl': '126px 248px',
        '--color-button-ghost-size-58xl': '128px 252px',
        '--color-button-ghost-size-59xl': '130px 256px',
        '--color-button-ghost-size-60xl': '132px 260px',
        '--color-button-ghost-size-61xl': '134px 264px',
        '--color-button-ghost-size-62xl': '136px 268px',
        '--color-button-ghost-size-63xl': '138px 272px',
        '--color-button-ghost-size-64xl': '140px 276px',
        '--color-button-ghost-size-65xl': '142px 280px',
        '--color-button-ghost-size-66xl': '144px 284px',
        '--color-button-ghost-size-67xl': '146px 288px',
        '--color-button-ghost-size-68xl': '148px 292px',
        '--color-button-ghost-size-69xl': '150px 296px',
        '--color-button-ghost-size-70xl': '152px 300px',
        '--color-button-ghost-size-71xl': '154px 304px',
        '--color-button-ghost-size-72xl': '156px 308px',
        '--color-button-ghost-size-73xl': '158px 312px',
        '--color-button-ghost-size-74xl': '160px 316px',
        '--color-button-ghost-size-75xl': '162px 320px',
        '--color-button-ghost-size-76xl': '164px 324px',
        '--color-button-ghost-size-77xl': '166px 328px',
        '--color-button-ghost-size-78xl': '168px 332px',
        '--color-button-ghost-size-79xl': '170px 336px',
        '--color-button-ghost-size-80xl': '172px 340px',
        '--color-button-ghost-size-81xl': '174px 344px',
        '--color-button-ghost-size-82xl': '176px 348px',
        '--color-button-ghost-size-83xl': '178px 352px',
        '--color-button-ghost-size-84xl': '180px 356px',
        '--color-button-ghost-size-85xl': '182px 360px',
        '--color-button-ghost-size-86xl': '184px 364px',
        '--color-button-ghost-size-87xl': '186px 368px',
        '--color-button-ghost-size-88xl': '188px 372px',
        '--color-button-ghost-size-89xl': '190px 376px',
        '--color-button-ghost-size-90xl': '192px 380px',
        '--color-button-ghost-size-91xl': '194px 384px',
        '--color-button-ghost-size-92xl': '196px 388px',
        '--color-button-ghost-size-93xl': '198px 392px',
        '--color-button-ghost-size-94xl': '200px 396px',
        '--color-button-ghost-size-95xl': '202px 400px',
        '--color-button-ghost-size-96xl': '204px 404px',
        '--color-button-ghost-size-97xl': '206px 408px',
        '--color-button-ghost-size-98xl': '208px 412px',
        '--color-button-ghost-size-99xl': '210px 416px',
        '--color-button-ghost-size-100xl': '212px 420px'
      },
      dark: {
        '--color-background': '#0a0a0a',
        '--color-surface': '#1a1a1a',
        '--color-surface-elevated': '#2a2a2a',
        '--color-border': '#333333',
        '--color-border-light': '#2a2a2a',
        '--color-text': '#ffffff',
        '--color-text-secondary': '#a0a0a0',
        '--color-text-muted': '#666666',
        '--color-primary': '#3b82f6',
        '--color-primary-hover': '#2563eb',
        '--color-primary-light': '#1e3a8a',
        '--color-success': '#10b981',
        '--color-warning': '#f59e0b',
        '--color-error': '#ef4444',
        '--color-info': '#06b6d4',
        '--color-shadow': 'rgba(0, 0, 0, 0.3)',
        '--color-shadow-light': 'rgba(0, 0, 0, 0.1)',
        '--color-overlay': 'rgba(0, 0, 0, 0.7)',
        '--color-overlay-light': 'rgba(0, 0, 0, 0.3)',
        '--color-gradient-start': '#1a1a1a',
        '--color-gradient-end': '#2a2a2a',
        '--color-code-background': '#1a1a1a',
        '--color-code-border': '#333333',
        '--color-table-header': '#1a1a1a',
        '--color-table-row': '#2a2a2a',
        '--color-table-row-hover': '#333333',
        '--color-input-background': '#1a1a1a',
        '--color-input-border': '#333333',
        '--color-input-focus': '#3b82f6',
        '--color-button-primary': '#3b82f6',
        '--color-button-primary-hover': '#2563eb',
        '--color-button-secondary': '#6b7280',
        '--color-button-secondary-hover': '#4b5563',
        '--color-button-success': '#10b981',
        '--color-button-success-hover': '#059669',
        '--color-button-warning': '#f59e0b',
        '--color-button-warning-hover': '#d97706',
        '--color-button-error': '#ef4444',
        '--color-button-error-hover': '#dc2626',
        '--color-button-info': '#06b6d4',
        '--color-button-info-hover': '#0891b2',
        '--color-button-ghost': 'transparent',
        '--color-button-ghost-hover': '#333333',
        '--color-button-ghost-text': '#a0a0a0',
        '--color-button-ghost-text-hover': '#ffffff',
        '--color-button-ghost-border': '#333333',
        '--color-button-ghost-border-hover': '#4b5563',
        '--color-button-ghost-primary': '#3b82f6',
        '--color-button-ghost-primary-hover': '#2563eb',
        '--color-button-ghost-primary-text': '#3b82f6',
        '--color-button-ghost-primary-text-hover': '#ffffff',
        '--color-button-ghost-primary-border': '#3b82f6',
        '--color-button-ghost-primary-border-hover': '#3b82f6',
        '--color-button-ghost-success': '#10b981',
        '--color-button-ghost-success-hover': '#059669',
        '--color-button-ghost-success-text': '#10b981',
        '--color-button-ghost-success-text-hover': '#ffffff',
        '--color-button-ghost-success-border': '#10b981',
        '--color-button-ghost-success-border-hover': '#10b981',
        '--color-button-ghost-warning': '#f59e0b',
        '--color-button-ghost-warning-hover': '#d97706',
        '--color-button-ghost-warning-text': '#f59e0b',
        '--color-button-ghost-warning-text-hover': '#ffffff',
        '--color-button-ghost-warning-border': '#f59e0b',
        '--color-button-ghost-warning-border-hover': '#f59e0b',
        '--color-button-ghost-error': '#ef4444',
        '--color-button-ghost-error-hover': '#dc2626',
        '--color-button-ghost-error-text': '#ef4444',
        '--color-button-ghost-error-text-hover': '#ffffff',
        '--color-button-ghost-error-border': '#ef4444',
        '--color-button-ghost-error-border-hover': '#ef4444',
        '--color-button-ghost-info': '#06b6d4',
        '--color-button-ghost-info-hover': '#0891b2',
        '--color-button-ghost-info-text': '#06b6d4',
        '--color-button-ghost-info-text-hover': '#ffffff',
        '--color-button-ghost-info-border': '#06b6d4',
        '--color-button-ghost-info-border-hover': '#06b6d4',
        '--color-button-ghost-size-sm': '8px 12px',
        '--color-button-ghost-size-md': '10px 16px',
        '--color-button-ghost-size-lg': '12px 20px',
        '--color-button-ghost-size-xl': '14px 24px',
        '--color-button-ghost-size-2xl': '16px 28px',
        '--color-button-ghost-size-3xl': '18px 32px',
        '--color-button-ghost-size-4xl': '20px 36px',
        '--color-button-ghost-size-5xl': '22px 40px',
        '--color-button-ghost-size-6xl': '24px 44px',
        '--color-button-ghost-size-7xl': '26px 48px',
        '--color-button-ghost-size-8xl': '28px 52px',
        '--color-button-ghost-size-9xl': '30px 56px',
        '--color-button-ghost-size-10xl': '32px 60px',
        '--color-button-ghost-size-11xl': '34px 64px',
        '--color-button-ghost-size-12xl': '36px 68px',
        '--color-button-ghost-size-13xl': '38px 72px',
        '--color-button-ghost-size-14xl': '40px 76px',
        '--color-button-ghost-size-15xl': '42px 80px',
        '--color-button-ghost-size-16xl': '44px 84px',
        '--color-button-ghost-size-17xl': '46px 88px',
        '--color-button-ghost-size-18xl': '48px 92px',
        '--color-button-ghost-size-19xl': '50px 96px',
        '--color-button-ghost-size-20xl': '52px 100px',
        '--color-button-ghost-size-21xl': '54px 104px',
        '--color-button-ghost-size-22xl': '56px 108px',
        '--color-button-ghost-size-23xl': '58px 112px',
        '--color-button-ghost-size-24xl': '60px 116px',
        '--color-button-ghost-size-25xl': '62px 120px',
        '--color-button-ghost-size-26xl': '64px 124px',
        '--color-button-ghost-size-27xl': '66px 128px',
        '--color-button-ghost-size-28xl': '68px 132px',
        '--color-button-ghost-size-29xl': '70px 136px',
        '--color-button-ghost-size-30xl': '72px 140px',
        '--color-button-ghost-size-31xl': '74px 144px',
        '--color-button-ghost-size-32xl': '76px 148px',
        '--color-button-ghost-size-33xl': '78px 152px',
        '--color-button-ghost-size-34xl': '80px 156px',
        '--color-button-ghost-size-35xl': '82px 160px',
        '--color-button-ghost-size-36xl': '84px 164px',
        '--color-button-ghost-size-37xl': '86px 168px',
        '--color-button-ghost-size-38xl': '88px 172px',
        '--color-button-ghost-size-39xl': '90px 176px',
        '--color-button-ghost-size-40xl': '92px 180px',
        '--color-button-ghost-size-41xl': '94px 184px',
        '--color-button-ghost-size-42xl': '96px 188px',
        '--color-button-ghost-size-43xl': '98px 192px',
        '--color-button-ghost-size-44xl': '100px 196px',
        '--color-button-ghost-size-45xl': '102px 200px',
        '--color-button-ghost-size-46xl': '104px 204px',
        '--color-button-ghost-size-47xl': '106px 208px',
        '--color-button-ghost-size-48xl': '108px 212px',
        '--color-button-ghost-size-49xl': '110px 216px',
        '--color-button-ghost-size-50xl': '112px 220px',
        '--color-button-ghost-size-51xl': '114px 224px',
        '--color-button-ghost-size-52xl': '116px 228px',
        '--color-button-ghost-size-53xl': '118px 232px',
        '--color-button-ghost-size-54xl': '120px 236px',
        '--color-button-ghost-size-55xl': '122px 240px',
        '--color-button-ghost-size-56xl': '124px 244px',
        '--color-button-ghost-size-57xl': '126px 248px',
        '--color-button-ghost-size-58xl': '128px 252px',
        '--color-button-ghost-size-59xl': '130px 256px',
        '--color-button-ghost-size-60xl': '132px 260px',
        '--color-button-ghost-size-61xl': '134px 264px',
        '--color-button-ghost-size-62xl': '136px 268px',
        '--color-button-ghost-size-63xl': '138px 272px',
        '--color-button-ghost-size-64xl': '140px 276px',
        '--color-button-ghost-size-65xl': '142px 280px',
        '--color-button-ghost-size-66xl': '144px 284px',
        '--color-button-ghost-size-67xl': '146px 288px',
        '--color-button-ghost-size-68xl': '148px 292px',
        '--color-button-ghost-size-69xl': '150px 296px',
        '--color-button-ghost-size-70xl': '152px 300px',
        '--color-button-ghost-size-71xl': '154px 304px',
        '--color-button-ghost-size-72xl': '156px 308px',
        '--color-button-ghost-size-73xl': '158px 312px',
        '--color-button-ghost-size-74xl': '160px 316px',
        '--color-button-ghost-size-75xl': '162px 320px',
        '--color-button-ghost-size-76xl': '164px 324px',
        '--color-button-ghost-size-77xl': '166px 328px',
        '--color-button-ghost-size-78xl': '168px 332px',
        '--color-button-ghost-size-79xl': '170px 336px',
        '--color-button-ghost-size-80xl': '172px 340px',
        '--color-button-ghost-size-81xl': '174px 344px',
        '--color-button-ghost-size-82xl': '176px 348px',
        '--color-button-ghost-size-83xl': '178px 352px',
        '--color-button-ghost-size-84xl': '180px 356px',
        '--color-button-ghost-size-85xl': '182px 360px',
        '--color-button-ghost-size-86xl': '184px 364px',
        '--color-button-ghost-size-87xl': '186px 368px',
        '--color-button-ghost-size-88xl': '188px 372px',
        '--color-button-ghost-size-89xl': '190px 376px',
        '--color-button-ghost-size-90xl': '192px 380px',
        '--color-button-ghost-size-91xl': '194px 384px',
        '--color-button-ghost-size-92xl': '196px 388px',
        '--color-button-ghost-size-93xl': '198px 392px',
        '--color-button-ghost-size-94xl': '200px 396px',
        '--color-button-ghost-size-95xl': '202px 400px',
        '--color-button-ghost-size-96xl': '204px 404px',
        '--color-button-ghost-size-97xl': '206px 408px',
        '--color-button-ghost-size-98xl': '208px 412px',
        '--color-button-ghost-size-99xl': '210px 416px',
        '--color-button-ghost-size-100xl': '212px 420px'
      }
    }

    const themeColors = isDark ? colors.dark : colors.light

    // Apply colors to root element
    Object.entries(themeColors).forEach(([property, value]) => {
      root.style.setProperty(property, value)
    })

    // Update system theme detection
    if ($isAuto) {
      updateSystemThemeDetection()
    }
  }

  // Update system theme detection
  function updateSystemThemeDetection() {
    const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)')

    function handleSystemThemeChange(e: MediaQueryListEvent) {
      if ($isAuto) {
        themeManager.setTheme('auto')
      }
    }

    mediaQuery.addEventListener('change', handleSystemThemeChange)

    // Cleanup
    return () => {
      mediaQuery.removeEventListener('change', handleSystemThemeChange)
    }
  }
</script>

<!-- This component doesn't render anything, it just manages theme state -->
