name: Docker

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build image
        working-directory: workstream-svelte
        run: docker build -t workstream-svelte:latest .
      # - name: Login to registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - name: Tag & push
      #   run: |
      #     docker tag workstream-svelte:latest ghcr.io/${{ github.repository }}/workstream-svelte:latest
      #     docker push ghcr.io/${{ github.repository }}/workstream-svelte:latest
